version: 0.2

phases:
  install:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region us-east-1)
  build:
    commands:
      - echo "CODEBUILD_SOURCE_VERSION = $CODEBUILD_SOURCE_VERSION"
      - docker build -t 648548064017.dkr.ecr.us-east-1.amazonaws.com/transactrx/suitecrm:$CODEBUILD_SOURCE_VERSION .
      - docker push 648548064017.dkr.ecr.us-east-1.amazonaws.com/transactrx/suitecrm:$CODEBUILD_SOURCE_VERSION
